### ISSUE TITLE
How about the PE reads from sample_seqs.py

### ISSUE THREAD

**Issue by yifangt** [peterjc/pico_galaxy#16]
I was wondering how your sample_seqs.py deals with PE reads to keep the "read-pair" while sampling.
Do the PE reads have to be interleaved?
Thanks!

**Comment by peterjc** [comment]
If you have interleaved paired reads, just tick the "Interleaved paired reads" option. Then you can get e.g. every 100th pair.

If you have two matching files, run the tool twice on both with the same settings (e.g. every 100th read), and you'll get two matching smaller files. Maybe I need to make the example in the help text more explicit?

**Comment by yifangt** [comment]
Thanks!
"Maybe I need to make the example in the help text more explicit?" --Not really, at first sight I was thinking your script will take two files for PE reads, and I did not realized "running twice" will do the trick.
Thanks a lot!
