### ISSUE TITLE
muscle datatype is not available

### ISSUE THREAD

**Issue by bgruening** [peterjc/pico_galaxy#23]
`align_back_trans` is using a datatype called muscle which is not known to Galaxy.

**Comment by peterjc** [comment]
Hmm. I wonder why I used that... it dates back to the first commit 421cd0fc13dbf281e9a741eb8aa6fa246ea1554c four years ago.

Muscle isn't one of the EMBOSS datatypes https://toolshed.g2.bx.psu.edu/view/devteam/emboss_datatypes/a89163f31369

How did you spot this? Is planemo now linting this (there's probably an enhancement request for that).

I think I should just remove it, right?

**Comment by bgruening** [comment]
@erasche and me trying to fix all warnings, error messages in our Galaxy instance and this was one of these. I have removed it locally - and yes planemo should lint for this.

**Comment by peterjc** [comment]
That's now live on the main and test Tool Shed, thank you!
