### ISSUE TITLE
Update get_orfs_or_cdss on toolshed

### ISSUE THREAD

**Issue by abretaud** [peterjc/pico_galaxy#29]
Hi,
I have a problem with get_orfs_or_cdss not working with conda's python3. It looks like it was fixed in version 0.2.3 on this gituhb repo, but was not updated on the main toolshed.
Would it be possible to do it?

**Comment by peterjc** [comment]
Done, thank you for letting me know!

**Comment by abretaud** [comment]
Thanks! it works now
