### ISSUE TITLE
rpy is no longer available / pure python venn_list

### ISSUE THREAD

**Issue by FredericBGA** [peterjc/pico_galaxy#32]
https://github.com/peterjc/pico_galaxy/blob/7b4f610f28598071979fa61fc19c56faf03fe91e/tools/venn_list/venn_list.xml#L5

With galaxy 19_01 I can not make a fresh install: 

```
PackageNotFoundError: Packages missing in current channels:

  - rpy
```

Maybe I can help with #12 ?

**Comment by peterjc** [comment]
Assistance welcome - rpy2 has come a long way and an update would be worthwhile.

I have not looked at what the Galaxy bundled tools are doing, but ``rpy2`` is in conda (v2.9.4 conda-forge, there are older copies on bioconda but I assume those are now deprecated).

**Comment by peterjc** [comment]
With @FredericBGA's work on #33 we can close this as soon as the Main Tool Shed is updated (we would ideally first test installing from the Test Tool Shed works as expected).

**Comment by peterjc** [comment]
This update is now on the main Tool Shed, https://toolshed.g2.bx.psu.edu/view/peterjc/venn_list/679b6323db03
