### ISSUE TITLE
coverage_stats fails with Galaxy version 20.01

### ISSUE THREAD

**Issue by Takadonet** [peterjc/pico_galaxy#35]
Getting following error below:

`in samtools_depth_opt_available
    return " -d/-m " in output
TypeError: a bytes-like object is required, not 'str'`

Script is expecting to be using Python 2.7.X but new default is Python 3.X hence why it is failing.

**Comment by peterjc** [comment]
There's probably a good way to tell Galaxy to call this with Python 2 (although in hindsight that might have been a sensible default).

I'd be happy to change this to Python 3 ready syntax instead....

**Comment by Takadonet** [comment]
Simply add it to the requirements section  that you need python 2.7.X . 

Perhaps to future proof, add python 3.X to the requirements section and change syntax in the script.

**Comment by Takadonet** [comment]
So a few things... That error is for version 0.5.0 and not for the latest version in the repository (0.1.0) Latest version is working with python 3.X but **not** available on the toolshed. 

Possible that you can push latest version and we close this issue?

**Comment by peterjc** [comment]
Indeed, https://toolshed.g2.bx.psu.edu/view/peterjc/coverage_stats/ currently has v0.0.5 - while https://testtoolshed.g2.bx.psu.edu/view/peterjc/coverage_stats/ has v0.0.6 (Python 3 support) and v0.1.0 (reworked API).

It looks like an oversight in not pushing that to the main Tool Shed, and doing so should be low risk.

(I had started looking into why the TravisCI tests had broken - multiple changes in the ecosystem including Galaxy dropping Python 2 support)

**Comment by Takadonet** [comment]
Thanks for taking a look into this. Certain labs run this tool every day for last few years. Have a temporary fix for them but permanent solution be better

**Comment by peterjc** [comment]
That's the main ToolShed updated (although not the cleanest history as I used the tarball from the test tool shed, which added a coverage_stats-1b5523d3d2c2/ folder; should be harmless). Are you able to confirm that works for you?

**Comment by Takadonet** [comment]
Works as expected thanks!

**Comment by peterjc** [comment]
Excellent, thank you! I did try doing an upload with planemo, but need to redo the authentication settings as I'm using a different machine while working from home.
