### ISSUE TITLE
Capture version of Promoter 2, NOD, WoLF PSORT

### ISSUE THREAD

**Issue by peterjc** [peterjc/pico_galaxy#8]
Reported by @peterthorpe5

**Comment by peterjc** [comment]
Also missing ``<version_command>`` in other tools, e.g. ``tmhmm2.xml`` and ``signalp.xml``

Notes:

```
$ java -jar $CLINOD/clinod-1.3.jar | grep -i "^NucleOlar localization sequence Detector"
NucleOlar localization sequence Detector v. 1.3b (13 May 2011) 
```

```
$ promoter -V
promoter 2.0a, May 2001, revised in Aug 2004
```

Tricky ones:

```
$ grep "is version" ~/bin/tmhmm 
# This is version 2.0c of tmhmm
```

This comment appears to be the only version indicator.

```
$ head ~/bin/signalp
#!/bin/sh

# SignalP 3.0a, May 2004
# 
# VERSIONS	3.0a	18 May 2004	launch
# 		3.0b	15 Dec 2005	bugfixes, see README
# 


SYSTEM=`uname -s`			# which platform?
```

(That was probably SignalP 3.0b but the text is inconsistent)

```
$ head /opt/WoLFPSORT_package_v0.2/bin/runWolfPsortSummary 
#!/usr/bin/perl -w
#
#  Author: Paul Horton (remnants of code from CJ Collier may remain).
#  Maintainer: Paul Horton.
#  Organization: Computational Biology Research Center, AIST, Japan
#  Creation Date: Summer 2004
#  Last Modification $Date: 2006/08/31 07:21:44 $
#  Copyright: Paul Horton
#  Licensing: Anyone may distribute this under the GNU public license. For other
#             license information contact: horton-p AT aist.go.jp
```

There doesn't seem to be a version, so use stated last modified date instead?

**Comment by peterjc** [comment]
Having fixed clinod and promoter2, I'm going to close this issue.

Sadly none of tmhmm2, signapl3 and WoLF-PSOST provide a simple way to reliably redetermine their version.

**Comment by peterthorpe5** [comment]
OK. Nice work Pete

**Comment by peterjc** [comment]
As an aside, I found a Galaxy bug in the parallelism feature during this work:
https://trello.com/c/PCjHetBw/2745-tool-versions-not-captured-if-using-parallelism-use-tasked-jobs

If ``use_tasked_jobs = False`` then the ``<version_command>`` tag is run prior to the ``<command>`` tag as expected.

If ``use_tasked_jobs = True`` then it appears that after splitting the input, none of the child-jobs include the ``<version_command>``.

**Comment by peterjc** [comment]
Actually closing issue.
